application: foodtruck-977
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  mime_type: "text/css"

- url: /js
  static_dir: js
  mime_type: "application/javascript"

- url: /img
  static_dir: img
  mime_type: "image/png"

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest

env_variables:
   GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'